# Generated by Django 2.2.6 on 2019-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0003_auto_20191103_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ket',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
